### ISSUE TITLE
RAML 1.0

### ISSUE THREAD

**Issue by sichvoge** [quilicicf/linter-raml#6]
Hi guys, the js parser has been around for quite some time already and is in its final version. Any plans to update your module?

**Comment by quilicicf** [comment]
Yes, there is. As for an ETA, I can't give any yet but shouldn't be long. I'll write a comment on this ticket so that you're notified.

**Comment by quilicicf** [comment]
Hey, @sichvoge. 
I've been playing around with the new parser and created a branch to support it. 
Unfortunately, switching to it now would imply a regression as the parser does not specify the file in which an error was found in case of error in an included file.

Should I create a ticket on raml-js-parser2 ? 
I'll publish as soon as I can support errors in included files.

PS: to reproduce:
- fork linter-raml
- run the following js code

``` js
var parser = require('raml-1-parser');
var AST = loadApiSync('/local/path/to/linter-raml/test/raml10/api.raml');
AST.errors();
```

Gives: 

``` js
[ { code: 11,
    message: 'specifying unknown facet:tititatatoto',
    path: 'api.raml',
    start: 24,
    end: 36,
    line: 1,
    column: 13,
    range: [ [Object], [Object] ],
    isWarning: false },
  { code: 11,
    message: 'string should match to ^[0-9|-]+$',
    path: 'api.raml',
    start: 1713,
    end: 1718,
    line: 54,
    column: 16,
    range: [ [Object], [Object] ],
    isWarning: false },
  { code: 11,
    message: 'specifying unknown facet:tititatatoto',
    path: 'api.raml',
    start: 24,
    end: 36,
    line: 1,
    column: 13,
    range: [ [Object], [Object] ],
    isWarning: false } ]
```

With errors 1 & 3 duplicated and specifying the main file instead of the included file.

**Comment by sichvoge** [comment]
There is a ticket for that explicit information (see [here](https://github.com/raml-org/raml-js-parser-2/issues/394)). Its currently in one of our branches and will soon be merged. I also currently try to standardize the output schema for errors.

**Comment by quilicicf** [comment]
Cool! 
I'll finish my implementation when this fix goes live.

**Comment by quilicicf** [comment]
Forgot to close this issue, RAML 1.0 is supported now.
